### ISSUE TITLE
RESUBMIT fails to set CONTINUE_RUN to TRUE in cim2.0.7 and clm4_5_1_r119

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime#152] opened 2015-09-03 17:35 UTC
Looking at the code, it looks like it should do this, but it doesn't work correctly. This is something that Sean Swenson found. If you manually set CONTINUE_RUN TRUE and set RESUBMIT, things work correctly. But, if on your initial run you set RESUBMIT, it doesn't resubmit on it's own like it should. I did this with clm4_5_1_r119 which uses cime2.07 with a simple case...

create_newcase -case clm5hydro_2deg -mach yellowstone -res f19_g16 -compset ICRUCLM45

Then set RESUBMIT to something above zero, setup, build and run the case.

**Comment by bertinia** [comment] 2015-09-10 17:42
Here's more information about this bug sent in by Kevin Reader:

I've set up a single-instance run of CESM1_4_beta06.
I'm still developing, so I set DOUT_S = false.
I ran a job with RESUBMIT = 0, and saw that the output looked right, 
so I submitted a 2nd job with RESUBMIT = 5.  The 2nd job ran, but
the 3rd job couldn't start, because one of the scripts couldn't find './$CASE.run'.
Since the scripts have been rewritten in perl, I can't debug this any farther.

I do remember reading that the new default mode of running is that $CASE.run submits
a $CASE.sh_archive job, which, in turn, submits the next $CASE.run.
But I've turned off the short term archiver, so the mechanism for
$CASE.run to submit the next $CASE.run seems to be broken.
Now I can't find that documentation.

I also saw the cesm1_4_beta07 announcement, and the note about the bug that made
$CASE.st_archive run on the same nodes as $CASE.run, instead of on 1 processor or node.
I've found where I can fix that (I think).

**Comment by billsacks** [comment] 2015-09-13 22:16
I have (inadvertently) reproduced Kevin Raeder's problem. As he did, I had set DOUT_S = FALSE, but RESUBMIT > 0.

$ cat cesm.stderr.255956 
WARNING getTiming2: 1 nprocs - running in mpiserial mode so no additional timing to be reported , exiting 
sh: ./test_hist_init_0913.run: No such file or directory

$ tail -3 cesm.stdout.255956 
Submitting CESM job script: test_hist_init_0913.run
: bsub  <  ./test_hist_init_0913.run 
Job submission failed

**Comment by jedwards4b** [comment] 2015-09-13 22:21
Hi Bill,

This is fixed in the branch we are working on for 1_5_alpha01a.   It's been
broken for several beta tags though and we'll need to discuss what we want
to do about them tomorrow.

On Sun, Sep 13, 2015 at 4:16 PM, Bill Sacks notifications@github.com
wrote:

> I have (inadvertently) reproduced Kevin Raeder's problem. As he did, I had
> set DOUT_S = FALSE, but RESUBMIT > 0.
> 
> $ cat cesm.stderr.255956
> WARNING getTiming2: 1 nprocs - running in mpiserial mode so no additional
> timing to be reported , exiting
> sh: ./test_hist_init_0913.run: No such file or directory
> 
> $ tail -3 cesm.stdout.255956
> Submitting CESM job script: test_hist_init_0913.run
> : bsub < ./test_hist_init_0913.run
> Job submission failed
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/152#issuecomment-139923236
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Closed as completed** 2015-09-18 21:32 UTC
Labels: type: bug report, topic:  scripts, CRITICAL
