### ISSUE TITLE
Testing copies output data into $CASEROOT/CaseDocs

### ISSUE THREAD

**Issue by mnlevy1981** [CESM-Development/cime#263] opened 2015-10-26 22:23 UTC
I filled up `/glade/p/work/mlevy` in a hurry (at the price of having several tests fail) and it looks like it's due to the test scripts copying output from the run directory to caseroot after the test finishes. I noticed it for ERI tests, but wouldn't be surprised if it happened for all tests... I wiped my work directory but reran the tests with caseroot on `/glade/scratch`:

```
$ du -h --max-depth=1 .
46G     ./ERI.T62_g16.C.yellowstone_intel.pop-default.151026-134021
114G    ./ERI.T62_g16.CECO.yellowstone_intel.pop-ecosys.151026-144103
172G    ./ERI.T62_g16.CECO.yellowstone_intel.pop-ciso.151026-144127
```

edit: to clarify, the above are the case dirs, NOT the run dirs. The run dirs are smaller (??)

```
$ du -h --max-depth=1 . | grep ERI.T62_g16 
28G     ./ERI.T62_g16.C.yellowstone_intel.pop-default.151026-134021
68G     ./ERI.T62_g16.CECO.yellowstone_intel.pop-ecosys.151026-144103
103G    ./ERI.T62_g16.CECO.yellowstone_intel.pop-ciso.151026-144127
```

**Comment by mnlevy1981** [comment] 2015-10-26 22:27
I should add that this is found in cime4.1.2 and cime4.1.3

**Comment by jedwards4b** [comment] 2015-10-26 23:14
Hi Mike,

I've got this fixed in my sandbox and will put in a pull request shortly.
Basically the problem is a too loose pattern match is copying all files with
__in_ in the name from the run directory into CaseDocs.

On Mon, Oct 26, 2015 at 4:27 PM, Michael Levy notifications@github.com
wrote:

> I should add that this is found in cime4.1.2 and cime4.1.3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/263#issuecomment-151302650
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Closed as completed** 2015-10-29 15:22 UTC
Labels: type: bug report, topic:  tests
