### ISSUE TITLE
seq_flds_nml mechanism to communicate with components.

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#284] opened 2015-11-05 18:16 UTC
The mechanism for component models to add exchange fields to the coupler is 
currently fragile and unclear.   Currently cam is doing it one way and pop another.

Using a NUOPC may offer a robust solution to this problem,
do we defer until we have a NUOPC based driver/coupler code or should we develop an interim solution as well?

**Comment by rljacob** [comment] 2015-11-09 04:59
Can you say more about the different ways CAM and POP are adding fields?

**Comment by billsacks** [comment] 2016-05-18 21:09
We can't remember exactly what was desired here. This may partly be a duplicate of #324 . Closing.

**Closed as completed by billsacks** 2016-05-18 21:09 UTC
Labels: type: enhancement request
